spring:
  application:
    name: test-service

  mail:
    username: test@example.com
    password: test-password

jwt:
  token-secret-key: secret
  token-expiration: 864000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.springframework: WARN
    com.amalitech.usermanagementservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

