name: Check Test Coverage

on:
  pull_request:
    branches: [ "staging", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test

      - name: Generate Coverage Report
        run: |
          mvn -B package --file pom.xml

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/test-coverage/jacoco.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/test-coverage/jacoco.xml
          token: ${{ secrets.TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage

      - name: Save Coverage To Environment Variable
        run: |
          echo "TOTAL_COVERAGE=${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_ENV
          echo "CHANGED_FILES_COVERAGE=${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_ENV

      - name: Check Coverage
        run: |
          echo "Total Coverage: $TOTAL_COVERAGE"
          echo "Changed Files Coverage: $CHANGED_FILES_COVERAGE"
          if (( $(echo "$TOTAL_COVERAGE < 80" | bc -l) )) || (( $(echo "$CHANGED_FILES_COVERAGE < 80" | bc -l) )); then
            echo "Insufficient Coverage!"
            exit 1
          fi

